//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variamos.DevOpsDsl
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DevOpsDsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DevOpsDsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Variamos";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DevOpsDslDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DevOpsDslCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DevOpsDslExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DevOpsDslCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDevOpsDslExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DevOpsDslCommandSetId), 0x0001);
	
		// Package identifier
		public const string DevOpsDslPackageId = "dcd1f89d-000b-4058-8a43-beac92073e9f";
		
		// Editor factory identifier
		public const string DevOpsDslEditorFactoryId = "35fae0cc-3108-4123-8cf1-c38d1633276a";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DevOpsDslModelExplorerToolWindowId = "4862bab5-3ef9-4f41-baf7-5415442935ef";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Variamos.DevOpsDsl
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DevOpsDslCommandSetId = "a28e071e-4094-4bbe-9fcb-0e4db1927be6";
	}
}