---
- name: Install Docker on Ubuntu
  hosts: dev  # or you can target specific groups like 'prod' or 'dev'
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the Docker stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose (optional)
      apt:
        name: docker-compose
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add the ubuntu user to the docker group (optional)
      user:
        name: ubuntu
        groups: docker
        append: yes
