# Use postgres/example user/password credentials
version: '3.9'
name: variamos_develop

services: 

  dbaws:
    image: postgres:14.8
    container_name: variamos_db_aws_develop
    hostname: variamos_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${VARIAMOS_MS_LANGUAGES_DB_PASSWORD}
      POSTGRES_USER: ${VARIAMOS_MS_LANGUAGES_DB_USER}
      POSTGRES_SSL: ${VARIAMOS_MS_LANGUAGES_DB_SSL}
    ports:
      - "5433:${VARIAMOS_MS_LANGUAGES_DB_PORT}"
    volumes:
      - variamos_pgdata_aws_develop:/var/lib/postgresql/develop/variamosdevelopdata148
    networks:
      - variamosnet_aws_develop

  admineraws:
    image: adminer
    container_name: variamos_pgadmin_aws_develop
    hostname: variamos_pgadmin
    restart: always
    ports:
      - 8080:8080
    networks:
      - variamosnet_aws_develop

  variamospleaws:
    image: jasotov/variamosple:develop
    container_name: variamosple_aws_develop
    hostname: variamosple
    ports:
      - 8000:3000
    networks:
      - variamosnet_aws_develop

  variamosmslanguagesaws:
    image: jasotov/variamos_ms_languages:develop
    container_name: variamos_ms_languages_aws_develop
    hostname: variamos_ms_languages
    ports:
      - 6000:4000
    networks:
      - variamosnet_aws_develop
    environment:
      - DB_HOST=${VARIAMOS_MS_LANGUAGES_DB_HOST}
      - DB_DATABASE=${VARIAMOS_MS_LANGUAGES_DB_DATABASE} 
      - DB_PORT=${VARIAMOS_MS_LANGUAGES_DB_PORT}
      - DB_SSL=${VARIAMOS_MS_LANGUAGES_DB_SSL}
      - DB_USER=${VARIAMOS_MS_LANGUAGES_DB_USER}
      - DB_PASSWORD=${VARIAMOS_MS_LANGUAGES_DB_PASSWORD}

  variamoslanguagesaws:
    image: jasotov/variamoslanguages_aws:latest
    container_name: variamoslanguages_aws_develop
    hostname: variamoslanguages
    ports:
      - 4000:3000
    networks:
      - variamosnet_aws_develop
    environment:
      - DB_HOST=${VARIAMOS_MS_LANGUAGES_DB_HOST}
      - DB_DATABASE=${VARIAMOS_MS_LANGUAGES_DB_DATABASE} 
      - DB_PORT=${VARIAMOS_MS_LANGUAGES_DB_PORT}
      - DB_SSL=${VARIAMOS_MS_LANGUAGES_DB_SSL}
      - DB_USER=${VARIAMOS_MS_LANGUAGES_DB_USER}
      - DB_PASSWORD=${VARIAMOS_MS_LANGUAGES_DB_PASSWORD}

  vmsdomainapplicationaws:
    image: jasotov/vms_domain_application:main
    container_name: vms_domain_application_aws_develop
    hostname: vms_domain_application
    ports:
      - 6001:8081
    networks:
      - variamosnet_aws_develop
    environment:
      - DB_HOST=${VARIAMOS_MS_LANGUAGES_DB_HOST}
      - DB_DATABASE=${VARIAMOS_MS_LANGUAGES_DB_DATABASE} 
      - DB_PORT=${VARIAMOS_MS_LANGUAGES_DB_PORT}
      - DB_SSL=${VARIAMOS_MS_LANGUAGES_DB_SSL}
      - DB_USER=${VARIAMOS_MS_LANGUAGES_DB_USER}
      - DB_PASSWORD=${VARIAMOS_MS_LANGUAGES_DB_PASSWORD}

networks:
  variamosnet_aws_develop:
  
volumes:
  variamos_pgdata_aws_develop:
